### ISSUE TITLE
java.lang.ClassCastException when running elki 7.0.1 on OpenJDK

### ISSUE THREAD

**Issue by haidelber** [elki-project/elki#55] opened 2019-01-21 09:47 UTC
I switched from Oracle JDK 8.x to Open JDK 11.x recently, now my simulation based on ELKI doesn't work any more.
The problem seems to be located in `ELKIServiceRegistry`

> java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at de.lmu.ifi.dbs.elki.utilities.ELKIServiceRegistry.<clinit>(ELKIServiceRegistry.java:53)

I guess I need to switch back to Oracle Java in the meanwhile.

**Comment by kno10** [comment] 2019-01-21 09:52
This has long been fixed in the git version.
Please use the latest github version.

Duplicate of #51

**Closed by kno10** 2019-01-21 09:52 UTC
